<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>BettergiCore</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DebugType>embedded</DebugType>
    <InvariantGlobalization>true</InvariantGlobalization>
    <PublishAot>true</PublishAot>
    <RuntimeIdentifier>android-arm64</RuntimeIdentifier>
    <StripSymbols>true</StripSymbols>
    <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
    <NoWarn>CA1416</NoWarn>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <IlcDisableUnhandledExceptionExperience>true</IlcDisableUnhandledExceptionExperience>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.11.0.20250507" />
    <PackageReference Include="Sdcb.PaddleOCR" Version="3.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="JniBridge.cs" />
    <Compile Include="MegaStubs.cs" />
  </ItemGroup>
</Project>
